version: 0.2
env:
  variables:
    APP_NAME: "angular-cicd-pipeline-demo"
phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - echo install process started
      - if [ -z "${BRANCH}" ]; then echo "BRANCH not set" && exit 1 ; fi
      - if [ -z "${ENVIRONMENT}" ]; then echo "ENVIRONMENT not set" && exit 1 ; fi
      - npm install && npm install -g @angular/cli@14.2.1
  build:
    commands:
      - echo build process started now
      - git checkout $BRANCH
      - ng build
  post_build:
    commands:
      - echo build process finished, we should upload to S3 now
      - cd dist/$APP_NAME
      - ls -la
      - aws s3 sync . s3://angular-cicd-pipeline-demo/$ENVIRONMENT --delete

