name: Build CI

on:
  pull_request:
    types: [ labeled ]

jobs:
  deploy:
    name: 'Build and Deploy'
    if: ${{ github.event.label.name == 'deploy' }}
    runs-on: ubuntu-latest

    steps:
      - name: 'checkout'
        uses: actions/checkout@v2
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-duration-seconds: 3600
          
      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: angular-cicd-pipeline-demo
          env-vars-for-codebuild: |
            BRANCH,
            AWS_ACCESS_KEY_ID,
            AWS_SECRET_ACCESS_KEY,
            AWS_REGION,
            ENVIRONMENT

        env:
          BRANCH: ${{github.event.pull_request.head.ref}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          ENVIRONMENT: development
          APP_NAME: angular-cicd-pipeline-demo